### ISSUE TITLE
DB migrations

### ISSUE THREAD

**Issue by NN---** [linq2db/linq2db#1311]
Is it any way to automate writing DB migrations as other ORM with code first like Django do ?

**Comment by NN---** [comment]
Perhaps for long term you are right, but in the beginning of the project, I would like to have something easy to use.
In the end I want to use purely linq2db, but starting with it means that I will spend too much time in some infrastructure code.

**Comment by sdanyliv** [comment]
I’m thinking about this many times, what we need here:

- something that can define model from objects, and allow add metadata that needed only on databse level
- extend schema provider to retrieve more data (indexes, constraints)
- model comparator
- new DDL statements
- migrations provider  (FluentMigrator, EF Core migrations, etc.)

A lot of work here, isn’t?

**Comment by NN---** [comment]
I would say that comparing schemas and migration generator can be sufficient for obvious cases.
E.g. https://github.com/djrobstep/migra

**Comment by sdanyliv** [comment]
I see the following tasks:

1. Extend schema and schema provider (at least for SQL server)
2. Schema serializer
3. Schema comparer
4. Migration generator to FluentMigrator or EF Migrations or plain SQL or **own** migration engine.

Useful scenario 1

- We already have database
- Run engine to get chema
- Store schema in file or in this database.
- Then modify database by third party tools.
- Run engine to get new schema
- Compare schema and generate migrations for existing migration engine.
- Store new schema or replace previous.

Everyting instead of schema provider can be done as separate project.

**Comment by sdanyliv** [comment]
Why not possible? It is migration engine and can do that easily.

**Comment by sdanyliv** [comment]
@jogibear9988, before starting implementing something just think how it will be used in real life and why it should be useful. There are a lot of db engines that have HUGE list of features and a lot of hints, custom types. PostgresSql - monstroid in this area, because of their addon system.

**Comment by jogibear9988** [comment]
sqlite does not support renaming etc... you need to create temp tables, wich is done by migrator.net 
fluent does not support it!

**Comment by jogibear9988** [comment]
i only thought it would be possible.

i am also no fan of automatic migrations

**Comment by MaceWindu** [comment]
Closing, as we don't have any plans and resources for this feature. Good candidate for external project/pr
