### ISSUE TITLE
SetCommand with anonymous parameters

### ISSUE THREAD

**Issue by thyn** [linq2db/linq2db#1362]
I'm trying to use custom serializer in SetCommand method using anonymous parameters. It doesn't work.

Details:

I have custom serializer for IList<BinaryTestItem>

non working version:

```c#
var count = connection.SetCommand("update BinaryTest set Items+= @tosave where id = @id", new 
		{
			id = toDo.Id,
			tosave = (IList<BinaryTestItem>) new[] { toSaveItem}
		}).Execute();

```
 After debugging source codes I've found that you are populating metadata  same way as you are populating data models. So it requires Attribute [Column] for !IsPrimitive types.

Working Version
```C#

public class c
{
	public Guid id { get; set; }
	[Column]
	public IList<BinaryTestItem> tosave { get; set; }
}
...

var records = connection.SetCommand("update BinaryTest set Items+= @tosave where id = @id", new c
		{
			id = toDo.Id,
			tosave = (IList<BinaryTestItem>) new[] { toSaveItem}
		}).Execute();


```

Is it possible to have custom logic for anonymous parameters?

**Comment by sdanyliv** [comment]
@thyn, it is not working in your case because we check that member should be scalar type.

You can implement custom `IMetadataReader` as show here for EF
https://github.com/linq2db/linq2db.EntityFrameworkCore/blob/master/Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs#L19
and enrich your classes automatically with column attribute.

You can do that once for whole application:
```cs
MappingSchema.Default.AddMetadataReader(new MyCustomMetadataReader());
```
Or for specific `DataConnection`:
```cs
var ms = new MappingSchema();
ms.AddMetadataReader(new MyCustomMetadataReader());
using (var db = new DataConnection(ms))
{
   /// or later
   db.AddMappingSchema(ms);
}
```
