### ISSUE TITLE
T4 mysql generates Table names in lowercase even if uppercase

### ISSUE THREAD

**Issue by luisvsilva** [linq2db/linq2db#1450]
T4 mysql generates Table names in lowercase, this will work if system is windows, 

But it will break on Linux as table names are case sensitive

### Steps to reproduce
Create a table with Uppercase Characters.

e.g. TestTable

Generated Code:

```
[Table("testtable")]
public partial class TestTable
```

### Environment details
linq2db version: *2.2.0*
Database Server: *MySql*
Database Provider: *MySql*
Operating system: *Windows*
Framework version: *.NET Core 2.1*

**Comment by MaceWindu** [comment]
Just tested it and it works properly - table names generated in the same case as they exist in mysql.

You observe this behavior, because mysql for Windows by default create tables with lowercased name.

You can change this behavior in ini file: https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html, or just manually rename table files in data\<dbname> folder.
