### ISSUE TITLE
Is there DataConnection.BeginTransactionAsync() ?

### ISSUE THREAD

**Issue by crucialize** [linq2db/linq2db#1497]
BeginTransactionAsync() method exists in EFcore, but doesn't exist in linq2db. Will the synchronise method DataConnection.BeginTransaction cause threadpool starvation?

**Comment by MaceWindu** [comment]
It depends on wether you have open connection or not. I've checked EFCore method (https://github.com/aspnet/EntityFrameworkCore/blob/4236dfd7f2789782cbba26bf0af15b04dfaf2a0c/src/EFCore.Relational/Storage/RelationalConnection.cs#L218) - they just call OpenAsync for connection in this case instead of Open.

Linq2db don't have Async version for BeginTransaction right now, but it will use connection, associated with your DataConnection/DataContext object, if it already exists and open.
So as workaround you need to ensure you have connection open and if not - open it using OpenAsync.

**Comment by crucialize** [comment]
@MaceWindu Thanks.
