### ISSUE TITLE
Surrogate mapping fields

### ISSUE THREAD

**Issue by frankiDotNet** [linq2db/linq2db#1630]
Hello,

I know you won't like this idea ;-)

From time to time I have the problem that my customers have different database structures. 
This is because I have a lot of versions of my application that  have to be supported for a longer time.

Now there are tables where some columns may not exist and some are removed.
From my application view it does not matter if a column exists or not. If a user does not have a specific version, this column is not displayed.

A solution could be something I wrote here [global defined expressions](https://github.com/linq2db/linq2db/issues/1188), but then I have always to trigger my tt file to generate the default values for each mapped class.

Another way would be to create only fluent builders for these classes, but I think this has not a good readability and I like to work with mapping attributes.

So my idea is to have a mapping attribute that acts like a surrogate.

```
[Table("PERSON")]
public class Person{
    [Column("NAME")]
    public string Name {get; set;}
    [Column("AGE")]
    public int Age {get; set;}
    [Column("EMAIL")]
    [Surrogate("EMAIL", "?")] // constructor that has fake column name and a default value
    public string Email {get; set;}
}

```
`select c.NAME, c.AGE, '?' as EMAIL from PERSON;`

Updates and inserts are skipped.
Based on a specific criteria I have an init method that adds the surrogate attribute with the existing column mapping. 
So the application works fine also if the column does not exist in the database.

**Comment by hahn-kev** [comment]
I'm not totally sure I understand what you want. But I think there might be 2 options. 

All the linq2db attributes support specifying a configuration. So maybe if you have 2 different product configurations, `config1` and `config2`. In `config1` the email column exists, and in `config2` it doesn't. So you could put these attributes on your `Email` property
```C#
[Column(Configuration = "config1")]
[NonColumn(Configuration = "config2")]
public string Email {get; set;} = "?"; //default value
```
Then the default value is just set to `"?"` when it doesn't exist.
Now I'm not sure if this works or not for you, maybe it's more dynamic then that. 

If it is more dynamic than that you could implement an `IMetadataReader` to tell Linq2Db what attributes each property should have 

However for either of these you would have to determine the columns in the database ahead of time, in order to do that I would use the SchemaProvider which you can access by calling this
`dataConnection.DataProvider.GetSchemaProvider().GetSchema(dataConnection)`

**Comment by MaceWindu** [comment]
It could be achieved already using calculated column:

```cs
[ExpressionMethod(nameof(GetMissingColumnExpr), IsColumn = true)]
public string? MissingColumn { get; set; };

static Expression<Func<Entity, string>> GetMissingColumnExpr() => p => "fake";
```
