### ISSUE TITLE
t4 templates are not showing in Visual Studio 2019

### ISSUE THREAD

**Issue by zdomokos** [linq2db/linq2db#1865]
I added the linq2db.postgres nuget package to a new project in vs 2019. 
The references are added, but the folder with the t4 templates is missing.

[OrmTest.txt](https://github.com/linq2db/linq2db/files/3509941/OrmTest.txt)

**Comment by sdanyliv** [comment]
Just tested. Created .NET Framework console application and install linq2db.PostgreSql package - templates appear.

Try to reinstall package again or clear NuGet cache.

**Comment by MaceWindu** [comment]
They actually installed, but for some reason not added to project by Visual Studio. You can just do it manually. But I would recommend you to recreate project as I wasn't able to identify what exactly in your project makes it to work like that and your project has pretty old header:
```xml
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```
vs WinForms project, created by VS2019
```xml
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```

I've created issue for [project system](https://github.com/dotnet/project-system/issues/5316) but I suspect it could be rejected due to old project version used. Who knows.

**Comment by MaceWindu** [comment]
Closing it as it is actually nuget or project-system issue

**Comment by MaceWindu** [comment]
Another reason why it will be a good idea to recreate project - if content files doesn't work, who knows what else is broken there

**Comment by zdomokos** [comment]
Tested again: it works perfect for .net core projects, but fails for .net framework 4.7.2

**Comment by MaceWindu** [comment]
What project template you use? Because this is not something I get from VS2019 for winforms project
