### ISSUE TITLE
Oracle  + CommandTimeout

### ISSUE THREAD

**Issue by lobster2012-user** [linq2db/linq2db#2018]
Hello
(oracle provider)
I have a long running command (select * from).
I can’t stop interrupting with non-settings, not forced calls (commandtimeout\connection.close\command.cancel). The problem is apparently in the native library. 
Are there any known solutions?

**Comment by sdanyliv** [comment]
Which provider do you use? 
I'm asking because linq2db supports at least two: `Oracle.Native`, `Oracle.Managed`

What we can do here:
- Try to switch to `Oracle.Managed` maybe they have fixed provider i newer versions.
- Managed provider supports asynchronous calls, for example `ToListAsync(cancellationToken)`. So, try to cancel `CancelationTokenSource`, possible it can interrupt your query. 
- Also try to run your query without **linq2db** to validate that it is a provider issue.

**Comment by lobster2012-user** [comment]
@sdanyliv Thank you for answer. (managed)
I asked a question on an oracle forum. I am closing the issue.
https://community.oracle.com/message/15524226#15524226
