### ISSUE TITLE
linq2db.sybase - REST API - System.ObjectDisposedException - Object name: 'Timer'

### ISSUE THREAD

**Issue by juhunter** [linq2db/linq2db#2038]
We are hosting a web service in .NET 4.6.1 on a Windows Server 2012 R2 x64 on IIS version 7.5.9600.16384 and the w3wp process is randomly crashing with the following error:

An unhandled exception occurred and the process was terminated.

Application ID: /LM/W3SVC/8/ROOT/{application pool}

Process ID: 15720

Exception: System.ObjectDisposedException

Message: Cannot access a disposed object.
Object name: 'Timer'.

StackTrace:    at System.Timers.Timer.set_Enabled(Boolean value)
   at Sybase.Data.AseClient.AseConnectionPool.ReturnConnection(AseConnectionImpl impl)
   at Sybase.Data.AseClient1.AseConnection.Close(Boolean disposing)
   at Sybase.Data.AseClient1.AseConnection.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at Sybase.Data.AseClient.AseConnection.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Finalize()
   at Sybase.Data.AseClient.AseConnection.Finalize()

------------------------------------------------------------

Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at System.Timers.Timer.set_Enabled(Boolean)
   at Sybase.Data.AseClient.AseConnectionPool.ReturnConnection(Sybase.Data.AseClient.AseConnectionImpl)
   at Sybase.Data.AseClient1.AseConnection.Close(Boolean)
   at Sybase.Data.AseClient1.AseConnection.Dispose(Boolean)
   at System.ComponentModel.Component.Dispose()
   at Sybase.Data.AseClient.AseConnection.Dispose(Boolean)
   at System.ComponentModel.Component.Finalize()
   at Sybase.Data.AseClient.AseConnection.Finalize()

------------------------------------------------------------

Faulting application name: w3wp.exe, version: 8.5.9600.16384, time stamp: 0x5215df96
Faulting module name: KERNELBASE.dll, version: 6.3.9600.19425, time stamp: 0x5d26b6e9
Exception code: 0xe0434352
Fault offset: 0x000000000000908c
Faulting process id: 0x3d68
Faulting application start time: 0x01d5cbda63c3e953
Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 13a97178-37d2-11ea-80eb-005056903b3b
Faulting package full name: 
Faulting package-relative application ID: 

------------------------------------------------------------

We encountered this error when creating a console application when we used a ThreadPool - even though we gave each thread its own DbContext they seemed to interfere with each other and we had to roll the application back to a single thread.

**Comment by sdanyliv** [comment]
Looks like it is a bug in standard Sybase ADO.NET provider.
Have you tried to use other provider for Sybase: `Sybase.Managed`?
We have implemented this one using this library https://github.com/DataAction/AdoNetCore.AseClient

**Comment by MaceWindu** [comment]
Actually looking at AseConnectionPool.ReturnConnection implementation (in decompiler), I would say you probably share connection between threads, which lead to race conditions, because it looks like (simplified):
```cs
if (!connection.Disposed)
{
    connection.Timer.Enable = true; // fails here, because connection timer disposed (probably by another thread)
    connection.Dispose();
}
```
if it is not the case, then you really hit some bug in provider. Unfortunatelly, SAP providers (both ASE and HANA) has pretty low quality (AKA enterprise quality).

**Comment by juhunter** [comment]
@MaceWindu Thank you. I guess what is confusing to me is we use this driver EVERYWHERE without any issues. This is the first project we decided to use linq2db and we run into this issue. 

@sdanyliv Thank you. I will take a deeper look into this.

**Comment by MaceWindu** [comment]
@juhunter, looked at provided stack trace once more and noticed what is wrong - it fails during GC finalization stage.
Which means connection was abandoned but wasn't disposed properly, because AseConnection.Dispose disables finalization internally. And I suspect associated timer was disposed by finalizer earlier, that's why it throws this exception.

Do you have any manual connection management code like AseConnection creation?

**Comment by MaceWindu** [comment]
Actually it's also AseConnection's bug. It shouldn't access timer from finalizer, or at least check it is alive... But triggering finalization on connection object is bad enough already

**Comment by juhunter** [comment]
@MaceWindu We don't have any manual connection management code, no. Still don't full get it because, as stated earlier, this provider is used by all of our applications (where we actually DO the creation of AseConnection, AseCommand, etc.) without problem. It's only when allowing linq2db to do this for us do we run into a problem.

I'll look at switching our providers. Thanks for all your assistance with this problem.

**Comment by sdanyliv** [comment]
It is difficult to understand what happened here without sharing code which may cause problem.
It can be async methods, sharing connection between threads, third party problem, how it was implemented earlier without linq2db wrapping.

Feel free to reopen issue if you need addition input.

**Comment by MaceWindu** [comment]
Found my crystal ball and it gave me idea. If we agree that only linq2db creates sybase connections, then it means you have at least one place in your code, where created DataConnection/DataContext is not disposed after use and associated connection left open till it collected by GC.

If it's so, I have an idea that it could be intentionally,  taking into account that you use it in API context, to make code like this work:
```cs
ActionResult Action()
{
   //using (var db = new DataConnection(...))
   var db = new DataConnection(...);
   {
        // don't want to materialize query in conroller action
        //return Json(db.query.ToList());
        return Json(db.query);
   }
}
```
For situations like that I would recomment to implement something like:
```cs
class JsonCustom : JsonResult
{
    public JsonCustom(object data, IDisposable dbContext) : base(data)
    {
        _context = dbContext;
    }

    // override serialization method and call context dispose after base method call
}
```

PS: changing provider to managed, will not help, as it only fix crash from native provider. Real issue here is to found out where connection is not disposed, or you will face connection pool starvation issue.
