### ISSUE TITLE
Running BulkCopy without parameters

### ISSUE THREAD

**Issue by AndrePScope** [linq2db/linq2db#2144]
Why BulkCopy run without parameters?

Simple insert generates SQL with parameters:

> db.Insert(new SubmissionFile() { Status = "Uploaded2"});

`INSERT INTO submission_files
(
	status,
	filename,
	created,
	created_by
)
VALUES
(
	:Status,
	:Filename,
	:Created,
	:CreatedBy
)`

But BulkCopy generates SQL without parameters:
>db.BulkCopy<SubmissionFile>(new List<SubmissionFile>()
{
	new SubmissionFile() { Status = "Uploaded" },
	new SubmissionFile() { Status = "Uploaded2"}
});

`INSERT INTO submission_files
(
	status,
	filename,
	created,
	created_by
)
VALUES
('Uploaded','\\',NULL,'0001-01-01'::date,NULL,'0001-01-01'::date),
('Uploaded2','\\',NULL,'0001-01-01'::date,NULL,'0001-01-01'::date)
`

So, does this implementation has a relation to productivity or is it some else?
Could I use bulk operation with parameters?

**Comment by MaceWindu** [comment]
Because it is easy to hit parameters limit with a lot of record. Probably we should add option to enable parameters here

**Comment by AndrePScope** [comment]
Yes, please. 
To use a parameterized query optionally, it would be great!

Thank you for the quick answer!

**Comment by sdanyliv** [comment]
@AndrePScope, which data provider do you use?
Try `BulkCopyType = BulkCopyType.MultipleRows`
```cs
db.BulkCopy(new BulkCopyOptions { BulkCopyType = BulkCopyType.MultipleRows },
  new List()
  {
     new SubmissionFile() { Status = "Uploaded" },
     new SubmissionFile() { Status = "Uploaded2"}
  });

```

**Comment by AndrePScope** [comment]
Hi @sdanyliv !
I do not how, but I missed your comment from Mar 26.
I use PostgreSQL. I tried to use  BulkCopyType.MultipleRows. The result is the same: SQL generates without parameters, the values included in SQL directly.

In fact, the case when necessary to insert some limited (not thousands) number of rows is typical.
So the possibility to insert data via BulkCopy with parameters will be really nice.

Do I understand correctly that this feature is planned not for the 3.0.0 version, but for the undefined version 3.X ?

**Comment by to11mtm** [comment]
I have some notes on this while I started looking into #2960 

I think this is not difficult, but we should do some refactoring to make it right. We can probably handle this in multiple phases:

#### Phase 1
- Pass in 'correct' `maxParameters` and `maxSqlLength` into `MultipleRowsCopyHelper(Async)`. We may need to refactor methods like `protected BulkCopyRowsCopied MultipleRowsCopy1(MultipleRowsHelper helper, IEnumerable source)` so that they can have the parameter length passed in, since they pass private funcs into `MultipleRowsCopyHelper(Async)` for begin/add/finish.
  - SQL Server: 2099 (technically 2100, but I believe the way ADO Provider works, query text is a parameter)
  - Oracle: 32767
  - Postgres: 32767
  - SQLite: 999 (I think newer versions may take more, but this is pretty safe)

 - Provide a Switch to prefer parameters on `BulkCopyOptions` (since it is a behavior change, should we default to OFF?)

 - MultipleRowsHelper right now only checks whether we have 'overflowed' on string or parameter length -after- we have added the row. We should consider something like below, where we track the parameter/length -before- we add the row, and if it overflows, back-off to complete the statement.
```
//in BasicBulkCopy.cs
protected static async Task<BulkCopyRowsCopied> MultipleRowsCopyHelperAsync<T>
//....
await foreach (var item in source.ConfigureAwait(Common.Configuration.ContinueOnCapturedContext).WithCancellation(cancellationToken))
			{
				helper.LastRowStringStartIndex    = helper.StringBuilder.Length;
				helper.LastRowParameterStartIndex = helper.ParameterIndex;
				addFunction(helper, item!, from);

				if (helper.CurrentCount >= helper.BatchSize || helper.Parameters.Count > maxParameters || helper.StringBuilder.Length > maxSqlLength)
				{
					helper.Parameters.RemoveRange(helper.LastRowParameterStartIndex, helper.LastRowParameterStartIndex-helper.Parameters.Count);
					helper.StringBuilder.Length =
						helper.LastRowStringStartIndex;
					finishFunction(helper);
					if (!await helper.ExecuteAsync(cancellationToken).ConfigureAwait(Common.Configuration.ContinueOnCapturedContext))
						return helper.RowsCopied;
				}
			}
```

#### Phase 2

Phase 1 provides us parameterized inserts, but is a naive implementation; every time, we will still be re-building the parameters in the INSERT statement, and creating new parameters.
 
 - In an Ideal state, I think we would be better to re-use parameters as long as data providers play nice with that.
 - I'm imagining something where after the first pass, we are able to track the indexes to see whether we are in an 'after first insert' scenario in whatever `addFunction` is passed in above snippet, and decide whether we need to append to the string or can re-use existing string and/or params.

**Comment by MihailsKuzmins** [comment]
@MaceWindu, @sdanyliv sorry for commenting on this old issue, but I have a concern about SQL server.
Provider name: "Microsoft.Data.SqlClient"
Linq2Db version: 6.0.0-rc.3

I must use `BulkCopyType.MultipleRows` and I have the following bulk copy options:
```cs
private static readonly BulkCopyOptions FallbackBulkCopyOptions = new()
{
	BulkCopyType = BulkCopyType.MultipleRows,
	MaxBatchSize = 250,
	UseParameters = true,
};
```

And then the following SQL is generated:
```sql
DECLARE @p1 BigInt -- Int64
SET     @p1 = -4134520337143594670
DECLARE @p2 VarChar(4000) -- AnsiString
SET     @p2 = N'abc'
DECLARE @p3 TinyInt(1) -- Byte
SET     @p3 = 0
DECLARE @p4 TinyInt(1) -- Byte
SET     @p4 = 1
DECLARE @p5 Int -- Int32
SET     @p5 = 1
DECLARE @p6 NVarChar(4000) -- String
SET     @p6 = NULL
DECLARE @p7 Int -- Int32
SET     @p7 = 0
DECLARE @p8 VarChar(4000) -- AnsiString
SET     @p8 = NULL
DECLARE @p9 TinyInt(1) -- Byte
SET     @p9 = 0
DECLARE @p10 NVarChar(4000) -- String
SET     @p10 = N'sql injection here?'
DECLARE @p11 DateTime2
SET     @p11 = DATETIME2FROMPARTS(2025, 10, 30, 22, 14, 57, 6358130, 7)
DECLARE @p12 BigInt -- Int64
SET     @p12 = 8449862949087450616
DECLARE @p13 VarChar(4000) -- AnsiString
SET     @p13 = N'cde'
DECLARE @p14 TinyInt(1) -- Byte
SET     @p14 = 0
DECLARE @p15 TinyInt(1) -- Byte
SET     @p15 = 1
DECLARE @p16 Int -- Int32
SET     @p16 = 2
DECLARE @p17 NVarChar(4000) -- String
SET     @p17 = NULL
DECLARE @p18 Int -- Int32
SET     @p18 = 0
DECLARE @p19 VarChar(4000) -- AnsiString
SET     @p19 = NULL
DECLARE @p20 TinyInt(1) -- Byte
SET     @p20 = 0
DECLARE @p21 NVarChar(4000) -- String
SET     @p21 = N'sql?'
DECLARE @p22 DateTime2
SET     @p22 = DATETIME2FROMPARTS(2025, 10, 30, 22, 14, 57, 6360132, 7)

INSERT INTO [tempdb].[dbo].[#myTable]
(
	[ID],
	[Param2],
	[Param3],
	[Param4],
	[Param5],
	[Param6],
	[Param7],
	[Param8],
	[Param9],
	[Param10],
	[Param11]
)
VALUES
(@p1,@p2,@p3,@p4,@p5,@p6,@p7,@p8,@p9,@p10,@p11),
(@p12,@p13,@p14,@p15,@p16,@p17,@p18,@p19,@p20,@p21,@p22)
```

Even though it looks like string manupulation is handled somehow (i.e. ' is escaped and changed to ''), but doesn't it create an SQL injection risk when string variables are passed to SQL directly? And if a parameter changes then the SQL string will also change, so I am wondering whether SQL server will need to process each query from the start (what I want to say is that if the same SQL string is executed - `INSERT INTO [tempdb].[dbo].[#myTable] ...` then the server knows the execution plan and can reuse it).

I'm not saying something is bad, but just want to confirm whether there are possible risks and performance drawbacks?

**Comment by MaceWindu** [comment]
`Declare` secion is not a part of a query but debug information with list of used parameters with type and value.
In any case, even when we generate literal, we apply required escaping logic

**Comment by MihailsKuzmins** [comment]
@MaceWindu thanks for the (too fast) reply. I did some investigation and confirmed it
before:
```cs
DataConnection.WriteTraceLine += (s, s1, arg3) => Debug.WriteLine(s);
```

after:
```cs
DataConnection.DefaultOnTraceConnection += info => Debug.WriteLine(info.Command?.CommandText);
```

The latter confirmed that correct commands are sent to the server. So WriteTraceLine prints all commands with parameter values for trace purposes, TIL.
