### ISSUE TITLE
Support for sql between

### ISSUE THREAD

**Issue by AK107** [linq2db/linq2db#217]
Sql.Between would be very useful. Almost every my project must be implemented manually as follows:

``` c#
[Sql.Expression("{0} BETWEEN {1} AND {2}", ServerSideOnly = true)]
public static bool Between<T>(T x, T low, T high) where T : IComparable<T>
{
    // x >= low && x <= high
    return x.CompareTo(low) >= 0 && x.CompareTo(high) <= 0;
}
```

**Comment by igor-tkachev** [comment]
What about this one:

```c#
[Sql.Expression("{0} BETWEEN {1} AND {2}", PreferServerSide = true)]
public static bool Between<T>(this T x, T low, T high) where T : IComparable<T>
{
    // x >= low && x <= high
    return x.CompareTo(low) >= 0 && x.CompareTo(high) <= 0;
}
```

Also I think we will need Nullable version.

**Comment by AK107** [comment]
>>What about this one:
Вполне. Зачем может понадобится PreferServerSide я в целом понимаю, но предпочитаю переписать запрос, чтобы оно таки на стороне базы отработало.

>>Also I think we will need Nullable version.
как-то так:

        [Sql.Expression("{0} BETWEEN {1} AND {2}", ServerSideOnly = true)]
        public static bool Between<T>(T? x, T? low, T? high) where T : struct, IComparable<T>
        {
              // всецело на ваше усмотрение
              throw new LinqException("The 'Between is server side only operator.");
        }

**Comment by jogibear9988** [comment]
ili: can we include this?

**Comment by ili** [comment]
It is included already [here](https://github.com/linq2db/linq2db/blob/b4998d6bf39ebbd55cb385335d0fcb9b45d82e35/Source/Sql/Sql.cs#L101)

**Comment by JechoJekov** [comment]
In my view the current implementation for nullable structs handles `null` values incorrectly (or at least counter-intuitively). `null` values should be completely ignored instead of actually compared. For example, `query.Where(x => x.Number.Between<int>(1, null))` should be evaluated as "Number >= 1" not as "Number between 1 and NULL".
A query like `query.Where(x => x.Number.Between<int>(null, null))` should be ignored altogether.

**Comment by JechoJekov** [comment]
In my view the current implementation for nullable structs handles null values incorrectly (or at least counter-intuitively). null values should be completely ignored instead of actually compared. For example, `query.Where(x => x.Number.Between<int>(1, null))` should be evaluated as `Number >= 1` not as `Number between 1 and NULL` which can never evaluate to `true`.

A query like `query.Where(x => x.Number.Between<int>(null, null))` should be ignored altogether.

**Comment by sdanyliv** [comment]
It should not. `Between` Is created for users who needs exactly this syntax and no additional optimisarions are applied.
Mabe you need something like this https://github.com/rsdn/CodeJam/blob/master/Main/src/Collections/QueryableExtensions.Ranges.cs#L128

**Comment by JechoJekov** [comment]
@sdanyliv Then in what case would anyone what to use `null` with the `between` operator? I do not see any possible cases even if your columns allow `null` since `null` cannot be used in a range.
