### ISSUE TITLE
Spaces result in invalid SQL

### ISSUE THREAD

**Issue by kevmal** [linq2db/linq2db#2403]
Spaces in properties/fields result in invalid SQL:

```f#

open System    
open LinqToDB
open LinqToDB.Mapping
open LinqToDB.Data

[<Table(Name = "records")>]
type Record =
    {
      [<Column(Name = "id"); PrimaryKey; Identity>]
      Id : int 
    }
let ``some int`` = 2
let q = 
    use db = new DataConnection(DataProvider.MySql.MySqlDataProvider(""),connectionString)
    let table : Record ITable = db.GetTable()
    query {
        for i in table do 
        where(i.Id = ``some int``)
        select(i)
    } |> string

q
```

Resulting SQL (value of q):
```sql
--   MySql
DECLARE @some int Int32
SET     @some int = 2

SELECT
	`i`.`id`
FROM
	`records` `i`
WHERE
	`i`.`id` = @some int
```

**Comment by sdanyliv** [comment]
Unexpected trick from F#, I think you know workaround ;)

**Comment by Edward-Alchikha** [comment]
If you want to have spaces in a column name, I've found that (for SQLite at least, though a quick search shows that MySQL should also support columns with spaces when wrapped in ``) you can choose to inline your parameters when creating your DataConnection. Here's some C# that does this:

```csharp
await using var connection = new DataConnection(ProviderName.SQLiteMS, connectionString)
                {InlineParameters = true};
```

@sdanyliv While I haven't tested your recent commit out in #2347 that replaces spaces with underscores, I suspect it's going to cause me a lot of trouble if it also affects inline parameters, since I require table names and column names to be able to have spaces in them. Could you provide a setting to disable the call to NormalizeParameterName?

**Comment by Edward-Alchikha** [comment]
As a workaround for variable names with spaces in them, you can inline parameters:

```csharp
var connection = new DataConnection(ProviderName.SQLiteMS, connectionString) {InlineParameters = true};
```
