### ISSUE TITLE
Support for DB2iSeries using Odbc and/or OleDb

### ISSUE THREAD

**Issue by travbeamo** [linq2db/linq2db#2473]
Now that Odbc & OleDb are available in .NetStandard, linq2db now supports both:
* [AccessODBCDataProvider](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/Access/AccessODBCDataProvider.cs)
* [AccessOleDbDataProvider](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/Access/AccessOleDbDataProvider.cs)

Could similar **Odbc & OleDb DataProviders** be implemented for **DB2 iSeries** using the code from [Linq2DB4iSeries](https://github.com/LinqToDB4iSeries/Linq2DB4iSeries) and using adapters below:
* [OdbcProviderAdapter](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/OdbcProviderAdapter.cs)
* [OleDbProviderAdapter](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/OleDbProviderAdapter.cs)

Possibly a native one (using clases in the _**IBM.Data.DB2.iSeries**_ namespace) could also be integrated similar to how [DB2ProviderAdapter](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/DB2/DB2ProviderAdapter.cs)  handles both zOS & LUW.

These new DataProviders could then be officially maintained here in the one place rather than as an external package?

The [Linq2DB4iSeries](https://github.com/LinqToDB4iSeries/Linq2DB4iSeries) works well but uses the [IBM.Data.DB2.iSeries](https://www.nuget.org/packages/IBM.Data.DB2.iSeries) nuget package which only supports .Net Framework and does not look to be actively updated anymore, 

These DataProviders could be tested by using [pub400.com](https://pub400.com/) which is free and public Server running IBM i 7.4. You can create your own user, you have 300MB of disk storage and two private libraries.

Connection Strings & Drivers details can be found here:
* https://www.connectionstrings.com/ibm-client-access-ole-db-provider/
* https://www.connectionstrings.com/ibm-i-access-odbc-driver/

I could also help with the testing if possible as I have access to DB2 iSeries versions v5.4 & v7.4 (via [pub400.com](https://pub400.com/)).

**Comment by sdanyliv** [comment]
@travbeamo, maybe you want to try implementing such driver by yourself? Any help is appreciated.

**Comment by nsarris** [comment]
I finally found some time to maintain the Linq2DB4iSeries project and I'm really close to an RC for version 3. All tests are passing, but I need to commit a couple of patches to linq2db to get it work. Let me give you a round up of the situation so far.

There are two sets of .net drivers available for the i Series. 

One is the IBM i Access Client package that is what the Linq2DB4iSeries nuget uses. This used to be license only but IBM has made it publicly available lately. This package contains a native .net provider, but also an ODBC and an OleDb provider. Linq2DB4iSeries uses the native .net provider, which doesn't work with core, because the of interop problems with the underlying managed components. None of the drivers also trully support async (they simply wrap the sync calls with Task.FromResult). I've tested the ODBC and OleDb drivers with net standard 2.0 and they seem to be working. This is a viable solution for netcore/netstandard/net5 driver and I'm going to start working on it after I'm done with the v3 release.

The other is the IBM Data Server Client package, which is the exact same set of drivers DB2LUW and DBzOs uses, but to use it on the i series you need a rather expensive client side license (DB2Connect). We have been using a customized version of Linq2DB4iSeries of the the past few years with this driver and it's working seamlessly. It has native support for net core, and also work with Entity Framework. However, yet again it is based on a clunky managed implementation under the hood so async is not supported. Yes, this goes for the DB2 driver as well. There is IBM no database product with async support for .net at the moment.  I plan to support this driver in Linq2DB4iSeries  as well.

**Comment by tb-mtg** [comment]
@nsarris Sounds promising.  You mentioned 

> One is the IBM i Access Client package that is what the Linq2DB4iSeries nuget uses. This used to be license only but IBM has made it publicly available lately. This package contains a native .net provider, but also an ODBC and an OleDb provider. 

How can I get this new publicly available package so I can help out.

**Comment by nsarris** [comment]
https://www-01.ibm.com/marketing/iwm/platform/mrs/assets?source=swg-ia

You will need to create an IBM account and login. After that download the ACS Windows App Pkg English (64bit)

**Comment by nsarris** [comment]
@tb-mtg v3.1.5 has been released with netstandard, OleDb ,ODBC and DB2Connect support. Please try it and let us know of any issues on our gihub project page.

@sdanyliv @MaceWindu

**Comment by travbeamo** [comment]
Side question.

Is there any reason the data providers are all based on DynamicDataProviderBase rather than the DataProviderBase?

Is there any performance differences using the dynamic one?

**Comment by nsarris** [comment]
The "Dynamic" in DynamicDataProvider means that it has no hard reference to the underlying ADO.net provider but rather uses a reflection based adapter to invoke provider specific code.

**Comment by travbeamo** [comment]
@nsarris I may be wrong but after downloading & trying the **ACS Windows App Pkg English (64bit)** package you mentioned, it still looks to target **.NET Framework**.

Is there any IBM.Data.DB2.iSeries package that targets either **,NET Standard** or **.NET core**?

**Comment by nsarris** [comment]
There are 3 providers in there, the native .net provider only targets .Net Framework.

The other two providers (ODBD / OleDb) are .net agnostic and you interface them through System.Data.Odbc and System.Data.OleDb which are supported in both .Net Framework and .Net Standard 2.0

**Comment by MaceWindu** [comment]
I will close it, as it is better if iSeries-related issues/features tracked by https://github.com/LinqToDB4iSeries/Linq2DB4iSeries
