### ISSUE TITLE
Linq method Single() produces Sql TOP 2

### ISSUE THREAD

**Issue by yarecky1** [linq2db/linq2db#2557]
Why `Single` produces `TOP 2`?

```c#
public class TestClass
{
    public int Id { get; set; }
}
```

```c#
using (var table = DbContext.CreateTempTable<TestClass>())
{
    var q = DbContext.GetTable<TestClass>().SingleOrDefault();
}
```

```SQL
SELECT TOP 2
    [a].[Id]
FROM
    [TestClass] [a]
```

### Environment details
linq2db version: 3.1.0
Database Server: MsAccess
Database Provider: OleDb
Operating system: Win10
.NET Framework: 4.7.2

**Comment by viceroypenguin** [comment]
To be able to enforce the semantics of `.Single()`. `.Single()` will throw an exception if there is more than one element in the enumerable. If we only select 1 item, we do not know whether there is a second item or not, so we cannot throw the exception. By selecting 2, we can enforce the behavior.

`.First()` will do `TOP 1`, because we only care about the first item, and not whether or not there are any additional items.

**Comment by yarecky1** [comment]
Understood. Closing. Thank you.
