### ISSUE TITLE
How to bind nested class or NotColumn properties using stored procedure?

### ISSUE THREAD

**Issue by sgashua** [linq2db/linq2db#2701]
```cs
public class Invoice
{
    [PrimaryKey, Identity] public int ID { get; set; }
    [Column, Nullable] public int UserID { get; set; }
    [Column, Nullable] public string InvoiceNumber { get; set; }
    [NotColumn] public string Name { get; set; }
    [Association(ThisKey="UserID", OtherKey="ID", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, IsBackReference=true)]
    public User InvoiceUser { get; set; }
}
public class User
{
     [PrimaryKey, Identity] public int ID { get; set; }
     [Column, Nullable] public string Name { get; set; }
}
```

Stored procedure
```sql
select a.*, b.* from Invoice a 
inner join User b on b.ID = a.UserID
```

Code
```cs
var invoice = context.QueryProc<Invoice>("SP_GetInvoice").ToList();
```

but `invoice.InvoiceUser.Name` or `invoice.Name` is null.

How to bind nested class or NotColumn properties?

**Comment by viceroypenguin** [comment]
The problem here is that the caller is unaware of the joins inside of the stored procedure. The only thing the caller is aware of is a flat table that includes columns: (ID, UserID, InvoiceNumber, Name, ID, Name). As such, there is no way to represent FK relationships in this table.

Two things to do:
1. You need to make sure that the ID column of the User table is not presented. If you have two columns with the same name (Invoice.ID and User.ID here), then l2db will not be able to distinguish between the two. In this case, you could `select a.*, b.Name as UserName`, as an example.
2. You need to create a dto that gets used temporarily that holds all of the columns. Once queried from the db, then you can map the values from the temporary dto to Invoice and User objects as desired, or to other upstream DTO objects as desired.

**Comment by sdanyliv** [comment]
OFFTOP @sgtagan, such stored procedures has to be rewritten to the LINQ. In case for sure if they are so simple.

**Comment by sgtagan** [comment]
> OFFTOP @sgtagan, such stored procedures has to be rewritten to the LINQ. In case for sure if they are so simple.

My developer team wants to use stored procedure. Most of my projects use LINQ but they want to use stored procedure in one of my projects. I do not like to work with stored procedure too.

**Comment by sdanyliv** [comment]
@sgtagan, its is so sad that you have no option to use LINQ here. So then you will need to do additional work.
Stored procedure should return aliases for selected fields
```sql
select 
   a.Id as a_ID, 
   a.UserId as a_UserID, 
   a.InvoiceNumber as a_InvoiceNumber,
   a.Name as a_Name,

   b.Id as b_ID,
   b.Name as b_Name
from Invoice a 
inner join User b on b.ID = a.UserID
```
Create helper class and apply mapping
```cs
class SP_GetInvoice_Result
{
    [Column("a_ID", ".ID")]
    [Column("a_UserID", ".UserID")]
    [Column("a_InvoiceNumber", ".InvoiceNumber")]
    [Column("a_Name", ".Name")]
    public Invoice Invoice { get; set; }

    [Column("b_ID", ".ID")]
    [Column("b_Name", ".Name")]
    public User User { get; set; }
}
```
Then you can query your proc
```cs
var invoices = context.QueryProc<SP_GetInvoice_Result>("SP_GetInvoice").ToList();
```
So, in conclusion. You have to do a lot of boilerplate instead of writing simple extension method
```cs
public static IQueryable<Invoice> SP_GetInvoice(this IDataContext db)
{
    return db.GetTable<Invoice>().LoadWith(x => x.InvoiceUser);
}

var invoices = db.SP_GetInvoice().ToList();
```
