### ISSUE TITLE
Hide primary key and other columns when generating T4 model

### ISSUE THREAD

**Issue by sgashua** [linq2db/linq2db#2753]
I have BaseModel that contains ID, CreatedDate, CreatedBy, ModifiedDate and ModifiedBy.

I have added BaseEntityClass = "BaseModel". How to hide these 5 columns in generated T4 model class in net core 3.1.10? NET 5 able to hide these columns but net core 3.1.10 cannot.

**Comment by MaceWindu** [comment]
You need to remove those columns from model. See some examples how to customize generation here https://linq2db.github.io/articles/T4.html#example-of-generation-process-customization

Last example `Replaces all property names...` is similar to what you need - you just need to remove columns instead of rename them.

**Comment by sgashua** [comment]
Thanks. Finally managed to get it.
