### ISSUE TITLE
Can never get a postgresql connection string to work

### ISSUE THREAD

**Issue by JudeaDumont** [linq2db/linq2db#2757]
I followed the instructions in the linkToDBTemplates.postGresql copy me file
It read the database perfectly and generated models, etc. perfectly. 

The problem is when I try to connect to the database to read anything with the actual linq.
The construction of the DB class generated by the tt file never works.

If I input any configuration string into the DB constructor I get 
`LinqToDB.LinqToDBException: 'Configuration '<insert connection string here>' is not defined.'`

I have the postgresql drivers for npgsql and odbc
The user and password are confirmed and work fine if I start an odbc connection.

Here are some connection strings I've tried:
`User ID=main_admin;Password=jeff;Host=localhost;Port=5432;Database=postgres;providerName=PostgreSQL`

`User ID=main_admin;Password=jeff;Host=localhost;Port=5432;Database=postgres;`
`Server=localhost;Port=5432;Database=postgres;`

`User Id=main_admin;Password=jeff;Pooling=true;MinPoolSize=10;MaxPoolSize=100;Protocol=3;`
`Server=localhost;Port=5432;Database=postgres;`

`User Id=main_admin;Password=jeff;Pooling=true;MinPoolSize=10;MaxPoolSize=100;Protocol=3;providerName=PostgreSQL`

If I don't pass a con string I get: 
           
LinqToDB.LinqToDBException: 'Configuration 'PostgreSQL' is not defined.'
It says PostgreSQL is not defined regardless of what I put in for a provider etc.

I have the connection string defined in appsettings.json and in the dev version:
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "ConnectionStrings": {
    "Default": "User ID=main_admin;Password=jeff;Host=localhost;Port=5432;Database=postgres;providerName=PostgreSQL"
  },
  "AllowedHosts": "*"
}
```

 and after looking at the walkthrough for asp.net for linq2db I tried to add this to startup.cs:
```cs
 services.AddLinqToDbContext<AppDataConnection>((provider, options) => {
                options
                .UsePostgreSQL(Configuration.GetConnectionString("Default"))
                .UseDefaultLogging(provider);
            });
```
            
The default connection string shows up fine. No exception here. 
           
I still cannot readout of the database upon trying to use the connection method described in the tt file:

```cs           
           using (var db = new PostgresDB()) //always fails
```                      
I've been at this for about 7 hours total just trying to get a connection to PostgreSQL and scrounging google for an answer. Can't seem to find anybody who has a similar issue.
           
Unfortunately, I am going to have to move on to another linq provider for postgresql due to this problem.

**Comment by MaceWindu** [comment]
You pass connection string to constructor parameter, that expects connection configuration name.

Right now T4 generates only `ctor(string configuration)` on data connection class by default. And with release, planned for today, we will add generation of `ctor(LinqToDbConnectionOptions options)` constructor (see #2629).

Your option is  to add required contructor that accepts connection string (or `LinqToDbConnectionOptions`) by extending generated partial class (check #2629 for directions)

`new PostgresDB("Default")` or `new PostgresDB()` doesn't work for you, because it looks for connection string in app.config by default and this doesn't work with .net core applications. If you want it to work this way, you need to setup configuration provider at `DataConnection.DefaultSettings`

**Comment by MaceWindu** [comment]
Check this one for some examples #1890

**Comment by JudeaDumont** [comment]
https://github.com/linq2db/linq2db/issues/1890#issuecomment-754437119

Issue solved here. Needs to be included in the readme.
