### ISSUE TITLE
Association Property names

### ISSUE THREAD

**Issue by myabdolmaleki** [linq2db/linq2db#2803]
hi

im using linq2db in my projects and its wonderful, but i have a question.

why it create property names like DeleteRecCarta22951Afds? but my Association Property Type is a List of DeleteRecordCatableFinancing class.

linq2db can generate association property name  like "DeleteRecordCatableFinancings"?

thanks a lot

**Comment by viceroypenguin** [comment]
Without seeing your schema or knowing which DB you're using, I'm not sure off the top of my head why it's generating that name for the FK link, but you can change it if you want. Open the `.tt` file you're using for generation and between the `Load<dbtype>Metadata()` call and the 'GenerateModel()' call, add this code:

```csharp
		GetFK("<tablename>", "<db_fk_name>")
			.MemberName = "DeleteRecordCatableFinancings";
```

This will tell the generator to use the new name instead of the one it defaulted to based on the FK name. You can do this for each FK that you want to change names for.

**Comment by viceroypenguin** [comment]
See [here](https://linq2db.github.io/articles/T4.html) for more information on how to modify the generated code.

**Comment by sdanyliv** [comment]
@myabdolmaleki, for such case we have introduced callback methods:
https://linq2db.github.io/articles/T4.html#configuring-generation-process
```cs
// Defines method to generate name for "one" side of association
Func<ForeignKey, string> GetAssociationExtensionSingularName
    = GetAssociationExtensionSingularNameDefault;
// Defines method to generate name for "many" side of association
Func<ForeignKey, string> GetAssociationExtensionPluralName
    = GetAssociationExtensionPluralNameDefault;
```

**Comment by myabdolmaleki** [comment]
Hi

Im looking for automatic way, these approaches you said are handy, my database is sql server.

Thanks

**Comment by sdanyliv** [comment]
I don't get that. Many users have different naming conventions. So we have implemented callback mechanism to define exactly what is needed.
