### ISSUE TITLE
BulkCopyType.MultipleRows could insert incorrect data into varchar columns in Firebird

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#2839]
Discovered by #2829

`MultipleRows` use sql like:
```sql
insert from (
select {columns} from rdb$database
union all
select {columns} from rdb$database
...
union all
select {columns} from rdb$database
)
```

If one of target columns is of varchar type it could result in column values padded with spaces due to following reasons:
- we specify column value as string literal which is typed as CHAR(literal_length)
- firebird converts subquery column type to CHAR(max_literal_len) (basically padding smaller values with spaces)
- values with padding inserted into target varchar column

To fix it we need to type string literals that target varchar column with varchar type (for all record or only for first one if it will be enough, needs testing).

**Comment by jods4** [comment]
This seem to affect test data insertion.

I've had to disable Firebird from test `LeadLagOverloads` (see #3423 for context), because when inserting this data:
```cs
var data = new Issue1799Table3[] 
{
	new() { ProcessID = 1, ProcessName = "One" },
	new() { ProcessID = 2, ProcessName = "Two" },
	new() { ProcessID = 3, ProcessName = "Three" },
	new() { ProcessID = 4, ProcessName = "Four" },
};
```
All `ProcessName` have been inserted with a length of 5 (I suppose that's the max length of `"Three"`), padded with spaces.
Tests expectations then fail, of course, because when we assert something is `"Two"`, it actually comes back from DB as `"Two  "`.
