### ISSUE TITLE
DataContext's Dispose method should be accessible in child classes

### ISSUE THREAD

**Issue by Nevca** [linq2db/linq2db#2853]
I have a class that inherits `DataContext` and I need some additional code on dispose.

The problem is that `DataContext`'s Dispose method is private and `IDisposable` is implemented explicitly, so I can't override it, nor can I implement `IDisposable` and call it.

A simple solution will be to make it `virtual` so inherited classes can override it if needed.

### Environment details
linq2db version: 3.1.3

**Comment by jogibear9988** [comment]
@Nevca maybe you could create a pull request for this issue?

**Comment by jogibear9988** [comment]
@MaceWindu @sdanyliv would this be a breaking change?
If someone has derived from DataContext and implemented it's own Dispose?

**Comment by viceroypenguin** [comment]
@jogibear9988 if implemented correctly according to [this](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose) document, then no, it would not be a breaking change. However, it would give users the chance to properly handle disposing by overriding `protected virtual Dispose(bool disposing);`, which is then expected to call `base.Dispose(disposing)` in the override.

If they have overridden the implementation of `IDisposable.Dispose()`, they would have marked it `new`, which means they have already introduced a breaking behavior, because the `DataContext.Dispose()` will not get called at all.
