### ISSUE TITLE
DNX / CoreCLR support

### ISSUE THREAD

**Issue by ronnyek** [linq2db/linq2db#304]
So I've tinkered with linq2db quite a bti, and only now tried to import it into a coreclr project. It looks like for my purposes (linq2db + postgres) it may be a simple change of consuming System.Data.Common instead of the System.Data namespaces from the desktop assemblies.

I'm just curious if there is anyway to build a coreclr compatible version of this? I'm relatively sure if I was to start with a new project and just suck in all the classes, I could probably get it to build, but seems like one off setups like that are less than ideal.

**Comment by pebezo** [comment]
I'm also interested in the future plans for this. In time .NET will move towards Core more and more. For now staying on .NET Framework is an option, but long term we'd like to move to Core. Thanks.

**Comment by ronnyek** [comment]
I want to host on linux/bsd, which means as far as I know, my options are... entityframework7 which isnt really an option =(

**Comment by pebezo** [comment]
Dapper is in the process of having a Core version, but it's not as nice as LINQ2DB :grin: It's all very early though.

**Comment by Centurys** [comment]
+1

**Comment by byme8** [comment]
+1

**Comment by igor-tkachev** [comment]
What project type are you looking for?

**Comment by ronnyek** [comment]
Ehh, just something that supports aspnetcore... sounds like an rc is right around the corner but also seems like there are probably a few little things that prevent the port as is. I believe some of the interfaces for db abstractions dont exist etc.

**Comment by ronnyek** [comment]
RC2 was just released and microsoft swears that this time its actually a RC. (the api's are complete, and only bug fixing will happen). Also, they brought back some of the system.data data abstractions... so the actual porting should be much easier

**Comment by teonivalois** [comment]
+1

**Comment by gsteinbacher** [comment]
+1

**Comment by ronnyek** [comment]
Supposedly some of the data abstractions actually came back for the rc2 and 1.0 release, so the changes actually shouldn't be TERRIBLE.

**Comment by gsteinbacher** [comment]
I played around with what it would take to make add support for .Net Core RC2 and 1.0 to Linq2Db.  In case anyone is curious here are some of the things I found that will need to change.

**NOTE:  I am not an expert in everything (or anything for that matter) in .Net Core so there may be equivalents that I just did not find.  If anyone knows of anything different than what I am saying here I would be interested in learning.**

- `Serializable` does not seem to be supported anymore so will probably need to put #if statements around the `[Serializable]` attribute.
- Retrieval of configuration information, i.e., `System.Configuration`, has changed so much of the code surrounding the retrieval of configuration information will need to change.
- Could not find ODBC in System.Data

**Comment by kekekeks** [comment]
BTW, there is no need to switch from csproj/MSBuild

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/target-dotnetcore-with-msbuild.md
![core](https://github.com/dotnet/corefx/raw/master/Documentation/project-docs/pcl-targets-dialog-net46-aspnetcore10.png)

**Comment by JCKodel** [comment]
I have ported PetaPoco to .net core (wasn't so hard). 
Someone able to help make a fork for .net core?

**Comment by pebezo** [comment]
There's talk of bringing more APIs from full to core in the 1.1 release (end of November ). Would it make sense to wait for that?

**Comment by ronnyek** [comment]
At the rate things are going... I'm skeptical the november date will be hit... it would be awesome
but I'm skeptical

**Comment by ronnyek** [comment]
https://icanhasdot.net/result?github=linq2db~2Flinq2db
Looks like this compatibility tester points out mostly the libraries for being problematic. I know postgres and sql server have updated libraries that are net standard compatible

**Comment by ili** [comment]
In general there are few big problems:
* System.Configuration - not supported any more. Ignore or replace?
* DbType.DbNull - no more present in the enumeration. Don't kwon what to do... Treat as int?
* DataTable class is dummy! And it has only internal constructor. But it is present in interfaces and used for scheme provider. Unclear what to do...
* Odbc, OleDb are not supported (no Access & SapHanaOdbc)

And in general data clients should support net core...

**Comment by ili** [comment]
If smb can make a fire test for core package it would be great.
Feed - https://www.myget.org/F/ili/api/v3/index.json

**Comment by ronnyek** [comment]
@ili how is that work going? I'd also be aware that @igor-tkachev has some checkins to a v2 branch. I'm really interested in seeing a .net core compatible build... as this is one of my bigger outstanding things that doesnt support net core. I'd love to not have to rely on mono on linux

**Comment by ili** [comment]
@ronnyek work is going hard... there are huge amount of bugs in VS2015 + .Net Core and a lots of time is wasted to find out the problem.
You can see the process in https://github.com/ili/linq2db/tree/netcore also tests & builds are here
* Core build: https://ci.appveyor.com/project/ili/linq2db 
* Regular build: https://ci.appveyor.com/project/ili/linq2db-lcrq5
* Nuget package should be available from https://www.myget.org/F/ili/api/v3/index.json

In general what we do have now:
* Build succeed
* Most tests are succeed for net40 & net45. Fire test is succeed for netstandard16
* Nuget package supports net40, net45, netstandard16

TBD
* Port tests to netstandard16 (it is open question because i'm afraid that some specifics of `Microsoft.Data.SQLite` may occur and it is needed for running tests)
* Support some portable platform (for now for me it is not clear what portable profile should be chosen)

I think that now you can try use current package for testing, and it would be great to know about the result. But because `app.config` is not supported by .Net Core, you should use manual configuration, or to provide your own configuration via `IConnectionStringSettings` as here https://github.com/ili/linq2db/blob/netcore/Tests/Tests.NetCore/ConfigurationTest.cs

**Comment by ronnyek** [comment]
I personally am ok with most of that. The configuration stuff could easily be replaced with a configuration place holder and have consumers inject the configuration (which they can grab from settings.config or whatever). Are you worried at all about the fact that @igor-tkachev seems to be implementing a bunch in the way of v2 (though it doesnt appear to be .net core)?

**Comment by ili** [comment]
@ronnyek i'v taken a look on changes in v2 brunch, in most cases it is now refactoring, i don't think that either we are doing the same, or it would be problems on merge.

**Comment by ronnyek** [comment]
@igor-tkachev is there a way we can sort of strategize this... so as not end up hugely far apart, for a better chance of re-integration? .net core project structure varies quite a bit from previous .net stuff. Also, I'm more than willing to dive in and help out wherever. I use linq2db currently quite a bit with oracle/postgres/mssql, but intend to extend our software to support mysql.

**Comment by ghostknight63** [comment]
@ili @igor-tkachev Do you have any ETA for this? Need this just to make a decision which ORM to choose for my ASP.NET Core / MySql project. Thanks!

**Comment by ronnyek** [comment]
@ghostknight63 does your app have to run in linux/mac right away? You can consume it in full framework, its just not pleasant, and introduces all sorts of inconveniences around forcing you to target net451.

That being said, I too would really like to be supported out of the get go. Instead of a fork of mine or @ili that supports it, but wont be updated with fixes/updates etc

**Comment by ghostknight63** [comment]
@ronnyek I need to run it on linux. So It seems that EF7 is the only option that makes sense. Don't have much time to wait for release/any certainity. Unfortunately.

**Comment by ghostknight63** [comment]
Well, I've tried to adopt what is available at `v2` branch at the moment.
- I've thrown away everything that prevented compilation, e.g. System.Configuration stuff. Guessing of Data Providers, all of the data providers (seems the issues with the are common, but I decided no to waste time on it). Just direct specification of MySqlDataProvider and Connection string. Also thrown away all the stuff with Schemas. Since DataTable class is empty. Thrown out the `Compatability` folder completely since it prevented compilation.
- I've fixed couple bugs in QueryNew.BuildQueryExpression - excessive parameter and type mismatch (IDataContext vs IDataContextEx).

All of that enabled me to run `db.Query<T>(queryString)` and `db.MyEntity.ToList().Select(p => new MyEntityViewModel{}).ToList;

`TableAttribute` seems to be ignored by mapping engine, that is annoying.

Double `.ToList()` here is required because of the issue described below.

But at the moment seems something is broken in TableExpressionBuilder, because I can not run even simple joins or `LoadWith`s like
```
from c in db.Child
join p in db.Parent on c.ParentId equals p.Id
select new
{
c.Description,
p.Name
}

```
or
```
db.Child.LoadWith(c => c.Parent).ToList()

It gives errors like ArgumentException: Expression of type 'System.Collections.Generic.IEnumerable`1[Child]' cannot be used for parameter of type 'LinqToDB.ITable`1[Child]' of method 'LinqToDB.ITable`1[Child] LoadWith[Child](LinqToDB.ITable`1[Child], System.Linq.Expressions.Expression`1[System.Func`2[Child,System.Object]])' or  Expression of type 'Child' cannot be used for return type 'ChildViewModel' (when I remove the intermediate `ToList()`) or similar.

All the stuff above took me about 3 hours. I will try to spend some more couple hours to fix described errors for myself. If I will succeed running at least simple linq queries and doing inserts and updates - I think I will go with my `cutted` version of the library. Because even in that form it would be way better than EF7 current state.

And will hope that project maintainers will release fully functional version soon.

A suggestion: why not to go with some subset of features at the moment? Like if there is no support for System.Configuration - just throw it out and let users specify Provider/Connection string. With ORM itself working it would be way much better than nothing.

And another suggestion is to release per-databaseEngine packages not all at once. For example if MySql (I'm pretty sure that it is one of the most wanted) is ready - release it, Please do not wait for solving issues with ODBC (what for we do need Access with .NET CORE on Linux? :) and SAP could wait).  That would be nice to have.

**Comment by ghostknight63** [comment]
Well, I've managed to fix all that I needed. At least at the moment. Choosing `v2` branch was a wrong decision. `master` ported easier and seems to work more reliable.

**Comment by ili** [comment]
@ghostknight63 where can i see your fixes?

**Comment by ghostknight63** [comment]
@ili I haven't it published anywhere. I can send it to you by email if you are interested in it. It is just a subset of what was in master branch.

**Comment by ili** [comment]
@ghostknight63 yes, please send it on chudinia at gmail com

**Comment by ili** [comment]
@all

we'v got first "tested" version: https://ci.appveyor.com/project/ili/linq2db/build/1.7.5.42/tests

for Core tests are done only for SQLite for now. Not everything is good:
* some tests are failed because some methods "are not found", for example `Floor` method... google says that it is "extended" method for SQLite but this says nothing to me... May be somebody can explain me this?
* some tests are failed with really strange errors, so i do think that there are some problems with Expressions in Core
* and the thing really makes me sad: `Tests.Linq.InheritanceTests.*` makes `dotnet test` to hung.

my current biggest problem is - i can't debug tests:
* test explorer does not see tests
* if i do attach to `dotnet` breakpoints are not hited

so if smb, can help me, it would be great

**Comment by ghostknight63** [comment]
Don't know about Visual Studio runner, R# would support it since 2016.3 (in EAP now, you can try it out).

I've solved issue with inserting nulls (Linq2Db refused to insert nulls and inserted empty values).
Here is the change: DataProviderBase:288 parameter.Value = value;// ?? DBNull.Value;

DbNull is treated as non-null and substituted with some default value (empty string for varchars, 0 for ints, etc).

**Comment by ili** [comment]
@ghostknight63 i see, thx, i think "null issue" should be implemented only via separate test, to make sure of no side effects for different providers.

**Comment by ili** [comment]
@all

Port is stable, tested with SQLite, Sql Server, MySql, PostgreSQL.
Main problem is SQLite, because `Microsoft.Data.Sqlite` uses official SQLite builds, so number of extended methods are not available (most math functions and some string, like `CharIndex`). In general better decision would be to write new data provider, but I do suppose that MS would make a possibility to use non official builds. So you are welcome to use package from MyGet (I'v posted feed earlier).
 
For now I'm little bit far from making pull request, because build should also support some portable frameworks.

**Comment by tb-mtg** [comment]
Is there any chance of including support for a DB2 iSeries (formerly AS400) Data provider. Code for this can be found below:
https://gist.github.com/tb-mtg/5aaf36df5cddda3dc6d8

**Comment by ili** [comment]
@all package was renamed to linq2db.core

@tb-mtg not really clear what to do with link you'v provided... it's better do do it from pull request

but in any way @igor-tkachev  is only one who can accept it.. (

**Comment by sdanyliv** [comment]
@tb-mtg, you have to create pull request and approve for @igor-tkachev, but i think you have to correct code convention first.

**Comment by tb-mtg** [comment]
@sdanyliv @ili pull request https://github.com/linq2db/linq2db/pull/462 has been created for new DB2iSeries data provider

**Comment by jogibear9988** [comment]
this can also be closed?

**Comment by ronnyek** [comment]
so far as I know, this has not actually been committed, just developed and sitting in pull requests and other peoples clones.

**Comment by devsoft** [comment]
@ronnyek actually it has been merged into master recently

igor-tkachev merged commit bc3df43 into linq2db:master a day ago
1 check passed

**Comment by jogibear9988** [comment]
so can sm. close?

**Comment by AlthalusDGr8** [comment]
Hi, Am interested in having a dot net core version of this library.  What is the status please? can it be used with MSSQL?
Thanks

**Comment by ili** [comment]
Yes we do support Core now, you can take packages from MyGet (all info is on main page/readme.md) 
We'll release to nuget soon after closing couple of issues (#480, #478)

**Comment by ronnyek** [comment]
I'm not seeing the target netstandard1.6 framework support on myget, is that to be expected?

**Comment by ili** [comment]
@ronnyek here it is https://www.myget.org/feed/linq2db/package/nuget/linq2db.Core

**Comment by ronnyek** [comment]
And the .postgres / .MySQL ./Oracle clients... I realize some of those aren't net core compatible yet... Will those be there as well eventually?

**Comment by ili** [comment]
Tested with:
* "System.Data.SqlClient": "4.1.0"
* "Microsoft.Data.SQLite": "1.0.0" / "1.1.0"
* "MySql.Data": "7.0.5-IR21"
* "Npgsql": "3.1.8"
