### ISSUE TITLE
Still, why not just ConfigureAwait(false)?

### ISSUE THREAD

**Issue by artelk** [linq2db/linq2db#3097]
I believe there is nothing in linq2db code that would require executing the continuations in the caller side sync context.
Example
```c#
public static async Task<List<T>> ToListAsync<T>(
	this IAsyncEnumerable<T> source, 
	CancellationToken        cancellationToken = default)
{
	var result = new List<T>();
	var enumerator = source.GetAsyncEnumerator(cancellationToken);
	await using (enumerator.ConfigureAwait(Common.Configuration.ContinueOnCapturedContext))
	{
		while (await enumerator.MoveNextAsync().ConfigureAwait(Common.Configuration.ContinueOnCapturedContext))
		{
			result.Add(enumerator.Current); // <---- THIS LINE
		}
	}

	return result;
}
```
I think there is no reason to make it execute "THIS LINE" in the UI thread (if the caller is an UI app).

**Comment by MaceWindu** [comment]
No big reason actually. When this option was introduced, I had little to nothing understanding of synchronization contexts, so I just added option to not waste time on researching it.
We need to ensure it is not needed and probably remove it in v4 then.

**Comment by Shane32** [comment]
Here is one of the best articles on `ConfigureAwait(false)` that I have read:

https://devblogs.microsoft.com/dotnet/configureawait-faq/

In short, assuming that the code does not mess with the `SynchronizationContext` or `TaskScheduler`, then library code should always use `ConfigureAwait(false)`, and application code should never use `ConfigureAwait(false)`.  This is basically because the application's `await` (which does not have `ConfigureAwait(false)`) will restore the synchronization context regardless of whether any of the library code did so.

The exception is if the library code executes a callback into the application code -- see quote here from the article above:

> As with all guidance, of course, there can be exceptions, places where it doesn’t make sense. For example, one of the larger exemptions (or at least categories that requires thought) in general-purpose libraries is when those libraries have APIs that take delegates to be invoked. In such cases, the caller of the library is passing potentially app-level code to be invoked by the library, which then effectively renders those “general purpose” assumptions of the library moot. Consider, for example, an asynchronous version of LINQ’s Where method, e.g. `public static async IAsyncEnumerable<T> WhereAsync(this IAsyncEnumerable<T> source, Func<T, bool> predicate)`. Does predicate here need to be invoked back on the original `SynchronizationContext` of the caller? That’s up to the implementation of `WhereAsync` to decide, and it’s a reason it may choose not to use `ConfigureAwait(false)`.

So for example if a callback is registered within `OnTraceConnection` like this typical one:

```cs
            OnTraceConnection = x => {
                if (x.TraceInfoStep != TraceInfoStep.BeforeExecute) return;
                Debug.WriteLine(x.SqlText);
            };
```

Then whether or not `ConfigureAwait(false)` was used would affect whether the `OnTraceConnection` callback was run on the thread within the synchronization callback.  So to be more specific (I'm guessing a bit here but bear with me), if a Windows Forms app had an `async void` button click event handler and called linq2db, and had `OnTraceConnection` set to do something like `TextBox1.Text = x.SqlText;`, the callback code would fail if `ContinueOnCapturedContext` was `false` because it would not be on the UI thread.  However, whether or not `ContinueOnCapturedContext` was `false` would not matter for any code after the call within the button click handler, as that would be restored to the proper synchronization context regardless.

So as a library developer, we can decide whether to:
  1. continue to support `ContinueOnCapturedContext`, or
  2. document that the callbacks will not be restored onto the original synchronization context and always use `ConfigureAwait(false)`.
