### ISSUE TITLE
Memory leak with Query<T>.ObjectOperation<T1>

### ISSUE THREAD

**Issue by rechkalov** [linq2db/linq2db#316]
I have detected a memory leak when using DataConnection with customized MappingSchema:

``` c#
var schema = new MappingSchema();
var builder = schema.GetFluentMappingBuilder();
builder.Entity<Foo>().HasPrimaryKey(x => x.Id);

while (true)
{
    using (var db = new DataConnection("Test"))
    {
        db.AddMappingSchema(schema);
        db.Insert(new Foo() { ... });
    }
}
```

The problem is that:
- MappingSchema instance is a part of key used in static readonly dictionary in Query<T>.ObjectOperation<T1> 
- MappingSchema is compared only by reference 
- method AddMappingSchema always creates a new instance of MappingSchema 

As a result for each new iteration cache is appended.

Maybe I am wrong, but looks like that ConfigurationID property of MappingSchema can be used in dictionary key instead of MappingSchema itself.

**Comment by MaceWindu** [comment]
We need to check it, I think I've seen change like that in latest commits from @igor-tkachev

**Comment by MaceWindu** [comment]
It was fixed by https://github.com/linq2db/linq2db/commit/27235fbedaed6017a321034c6c2c484c3e592af1, which was  a part of 1.8.1 release. I didn't found a good way to write regression test, so I've just checked that ObjectOperation cache is not polluted by duplicate entries using debugger and memory profiler.

**Comment by rechkalov** [comment]
Thank you.
