### ISSUE TITLE
Is it possible to make it skip adding OR statement in joins

### ISSUE THREAD

**Issue by dagtveit** [linq2db/linq2db#3387]
code 
```
                from cat in _reportingDbContext.GlCategories
                    .Where(x => x.ReportType == "Balance")
                from cato in _reportingDbContext.GlCategoryOverrides
                    .Where(x => x.CustomerId == customerId)
                    .LeftJoin(pr => pr.ExternalAccountNo.ToString() == cat.ExternalAccountNo.ToString() )
```

produces this on statement in sql if the properties are nullable
```
`ON (t1."ExternalAccountNo" = y_1."ExternalAccountNo" OR t1."ExternalAccountNo" IS NULL AND y_1."ExternalAccountNo" IS NULL)

```

but if they are not nullable 
`ON (t1."ExternalAccountNo" = y_1."ExternalAccountNo" )`

Is it possible to force this away as this is a huge performence killer. 54 ms vs 277 ms for a small dataset. almost 6x slower performence

**Comment by sdanyliv** [comment]
You can set global configuration to do not do that:
```cs
Configuration.Linq.CompareNullsAsValues = false;
```

**Comment by dagtveit** [comment]
Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MaceWindu** [comment]
I think wrapping field into `Sql.AsNotNull` should also help. At least it doesn't disable IS NULL  checks globally

**Comment by dagtveit** [comment]
Thx also for the tip. But why do I want it. I haven't come across a situation where I need it yet. Any examples?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MaceWindu** [comment]
It depends on what kind of semantics you expect for specific comparison: SQL or C#

```sql
select t1.c as t1c, t2.c as t2c,
case when t1.c = t2.c THEN 'true' ELSE 'false' END as equals_sql,
case when t1.c = t2.c or (t1.c is null and t2.c is null) THEN 'true' ELSE 'false' END as equals_csharp,
case when t1.c <> t2.c THEN 'true' ELSE 'false' END as not_equals_sql,
case when t1.c <> t2.c or (t1.c is null and t2.c is not null) or (t1.c is not null and t2.c is null) THEN 'true' ELSE 'false' END as not_equals_csharp
FROM
(select 1 as c union select 2 union select null) as t1
cross join 
(select 1 as c union select 2 union select null) as t2
```
![image](https://user-images.githubusercontent.com/1099238/146673725-442d8830-aba9-405d-8176-ce8e6fa91525.png)

**Comment by jods4** [comment]
@dagtveit There's no situation where "you need it" as a global option. 
If you need it for a particular query, there's a [`a.Is[Not]DistinctFrom(b)` method](https://github.com/linq2db/linq2db/pull/2946) that works exactly like C# `!=` (resp. `==`) and generates the best code, given what your provider supports and the known nullability of its arguments.

In the end I think it's more a mindset, this feature is likely to have been copied from EF, which proposed "C# semantics" in queries as well.

Personally I like to think of linq2db as type-safe SQL queries. I want my code to have a direct, predictable translation to SQL and I'm aware that nulls don't work the same in SQL as they do in C#. That's why I always use `CompareNullsAsValues = false` myself.

Two more remarks:
- Adding `or (a is null and b is null)` (assuming you don't need it) can hurt execution plans if the query was meant to use an index on `a` or `b`;
- `CompareNullsAsValues` tends to be problematic for more complex features. Linq2db tries to apply it wherever it makes sense, such as `a IN (1, 2)` but it's just not always possible, so the semantics have their limits. Two examples of this: (1) I tried to provide users more control over the `IN` construct to avoid any additional, unwanted SQL code -- and it turned out to be a big complicated mess; (2) I'm working on adding SQL row constructors (aka tuples) and it's just not practical to enforce C# semantics there, so I dropped the ball -- on `CompareNullsAsValues`, not on the row ctors 😄.
