### ISSUE TITLE
Generate entity-class-name with underscores - CLI

### ISSUE THREAD

**Issue by meld-cp** [linq2db/linq2db#3676]
First off, thank you for developing this project, it's awesome!

### My Issue
I have tables named like this: `se_AuthDevice`
and I would like entity classes named the same, like this: `se_AuthDevice`

### Steps to reproduce

I've tried:
```json
{
    "dataModel": {
        "entity-class-name": {
          "case": "none",
          "pluralization": "none"
        }
    }
}
```
which get me entity names like: `seAuthDevice` (close, but missing the underscore)

and if I try:
```json
{
    "dataModel": {
        "entity-class-name": {
          "case": "none",
          "pluralization": "none",
          "transformation": "t4"
        }
    }
}
```
I get the following error:
```
Cannot parse option value (--import config.json): JSON (config.json): cannot parse option 'dataModel.entity-class-name' value '{
      "case": "none",
      "pluralization": "none",
      "transformation": "t4"
    }' : transformation : unknown value: 't4'
```
but the `dotnet-linq2db help scaffold` docs say that ` "transformation": "t4"` is a valid option.

So I guess there are 2 issues here:
1. How do I generate class names with underscores like: `se_AuthDevice`
2. The ` "transformation": "t4"` option in `dataModel.entity-class-name` isn't working, should it be?

### Environment details
linq2db version: 4.1.1.0
Database Server: MS SQL 2012
Database Provider: SQLServer
Operating system: Win10
.NET Framework: .NET 6.0

**Comment by MaceWindu** [comment]
1. `t4` is a `case` value, not `transformation`. This a bug in help generator - it should show `association` here instead of `t4` https://github.com/linq2db/linq2db/issues/3678
2. there is `transformation: none` option that should do what you need, but currently it is not accepted (bug). You can implement interceptor and set this option in interceptor constructor (options could be passed to interceptor constructor and modified there) https://linq2db.github.io/articles/CLI.html#customize-scaffold-with-code

**Comment by meld-cp** [comment]
Thanks @MaceWindu, yes I think using the interceptor dll will be the most flexible and I can add logging etc.

Would there be any way to attach the debugger and get it to hit a breakpoint? 🤔

**Comment by MaceWindu** [comment]
In such cases I usually add `System.Diagnostics.Debugger.Launch();` to code I want to debug

**Comment by meld-cp** [comment]
Works great, thank you
