### ISSUE TITLE
Oracle provider goes banana when column type changes

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#3894]
Discovered by tests from #3893

Tests recreate table with same name for table and columns but different column type. Results in incorrect type reported for column by provider and wrong data read methods used and wrong data returned from reader in general.

E.g. for `string Stamp` column provider reports it's type as number resulting in following read expression:
![image](https://user-images.githubusercontent.com/1099238/209470495-ef31fc0d-16c3-44d1-8572-943fd5a0f3a5.png)

Also text data from column interpreted by provider as decimal resulting in complete nonsense:

![image](https://user-images.githubusercontent.com/1099238/209470521-b5a19802-df4b-4177-a87e-c3f1098be008.png)

PS: Probably we cannot do anything here if there is no some provider reset logic.

**Comment by jods4** [comment]
@MaceWindu This is caused by server-side _Statement Caching_.
You can read about it here: https://docs.oracle.com/cd/E85694_01/ODPNT/featOraCommand.htm#ODPNT271

The fact that the statement cache is not cleared when its dependencies (objects) are modified or even dropped could be considered a bug... but hey it's Oracle what did you expect?

You have a few options to work-around this. They impact performance so I wouldn't include any of them in linq2db provider code itself but you can use them in your tests.

1. `OracleCommand.AddToStatementCache = false` on commands whose underlying schema is gonna change (could be implemented in tests through an interceptor)
2. `OracleConnection.PurgeStatementCache()` to completely clear all cached statements from a connection (notice that the cache applies throughout the lifetime of a _pooled_ connection, this behavior is controllable through a connection string parameter)
3. `Statement Cache Size=0` in connection string to completely disable statement caching (impact perfs, obviously).

**Comment by MaceWindu** [comment]
Thanks!

Nothing to do here, so closing
