### ISSUE TITLE
Boolean to MS Access Boolean

### ISSUE THREAD

**Issue by longdog** [linq2db/linq2db#409]
Insert and Update operation are not convert Boolean to  Boolean (Yes/No) in MS Access.
Select operation works correct.

For example, I have a table "products" with field "cond" (Yes/No type)
T4 Models generated class products with field

```
[            Identity] public bool    cond      { get; set; } // Bit
```

Code

```
products = from p in db.products select p;
```

returns correct cond value (true or false),

Code

```
var product;
...
product.cond = true;
...
db.Insert(product);
```

code do not modify field in the database (other fields inserted correct).

**Comment by AndreasWaning** [comment]
I have the same Problems I am still wait for a solution this 1 year

**Comment by VictorHaine** [comment]
T4 model generation for MS Access makes the boolean properties "Identities", so you need to get rid of it.

**How I Fixit:**
In the main .tt file, the one you need to copy and rename, I modified all the bool columns to remove the Identity attribute.
So far so good. The problem is: when you remove Identity Attribute, it automatically becomes ignored on Insert and Update queries. You need to set these properties of the Column to false: _SkipOnUpdate_ and _SkipOnInsert_.

Something like this goes before generate models:

```C#
GetColumn("Person", "SomeBoolField"). IsIdentity = false;
GetColumn("Person", "SomeBoolField"). SkipOnUpdate = false;
GetColumn("Person", "SomeBoolField"). SkipOnInsert = false;
````

**Comment by AndreasWaning** [comment]
Hello Victor,when I removed the Identity Attribute, it works fine.

But I do not understand, where I can changes this:
GetColumn("TableName", "SomeBoolField").IsIdentity = false;
GetColumn("TableName", "SomeBoolField").SkipOnUpdate = false;
GetColumn("TableName", "SomeBoolField").SkipOnInsert = false;
