### ISSUE TITLE
LoadWith not working in MARS mode equal false

### ISSUE THREAD

**Issue by ingrad** [linq2db/linq2db#440]
All tables in "CustomDataBase"
`ConnectionString = "Server=*;user id=*;password=*"`

```
d.Connection.ChangeDatabase("CustomDataBase");
LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = true;

d.GetTable<Table>().LoadWith(c => c.SubTable)
```

Error "Invalid object name 'SubTable'"

if
`ConnectionString = "Server=*;user id=*;password=*;MultipleActiveResultSets=True"`
worked

**Comment by SlowLogicBoy** [comment]
Do SubTable property has [Association(...)] Attribute?

**Comment by ili** [comment]
Have you solved an issue?
What SQL is generated?
As for me it looks like that `d.Connection.ChangeDatabase("CustomDataBase");` does not changed database (some connection re init may be occurred)...

**Comment by ili** [comment]
this has the same problem as for #482 

If MARS disabled for connection new connections would be created, so your `d.Connection.ChangeDatabase("CustomDataBase");` would not be applied... 

This is `By Design` for now, if you do need to connect to multiple databases use multiple configurations, and create connection with specifying configuration name.
