### ISSUE TITLE
There is already an open DataReader associated with this Command which must be closed first

### ISSUE THREAD

**Issue by Quentinb** [linq2db/linq2db#441]
I'm using Ling2DB in a WebAPI against a SQL server database and receive a "There is already an open DataReader associated with this Command which must be closed first" error consistently. I have tried adding .toList() after a GetTable<T>() as well as after a linq query. I've also added the "MultipleActiveResultSets=True" into the connection string with no resolution and have added the "LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = true;"

If I use something like the blow, it breaks nicely, everytime!
GetTable<T>().OrderBy(x => Guid.NewGuid()).FirstOrDefault()

**Comment by ili** [comment]
It looks like you are caching `DataConnection` object.
You can use `DataContext` class for single queries or `using` pattern while working with `DataConnection`

**Comment by ili** [comment]
Closing an issue because of no feedback

**Comment by rex-pj** [comment]
I still got this issue while using AddLinqToDbContext as the example here, https://linq2db.github.io/articles/get-started/asp-dotnet-core/index.html
Change the ServiceLifetime to Transient is not the good practices.
Do you have any ways else or guide doc to solve this issue?
Thank you!

**Comment by sdanyliv** [comment]
@rex-pj, please open new issue with more details.

**Comment by dipique** [comment]
Since this is the top google result for this issue, I wanted to add my solution. None of the others (e.g. MARS) were working for me.

I had written an extension method to call a stored procedure and return its value. This was I wrote by hand, but I have had similar issues with T4 generated stored procedures. The method looked like this:

    public static string GetRecordStateXml(this L2DB db, string tableName, string primaryKeyName, int id)
    {
        db.QueryProc<int>("dbo.GetRecordStateXml",
            new DataParameter("@TableName",      tableName,      DataType.VarChar),
            new DataParameter("@PrimaryKeyName", primaryKeyName, DataType.VarChar),
            new DataParameter("@DataRowId",      id,             DataType.Int32),
            new DataParameter("@XML",            null,           DataType.Xml) { Direction = ParameterDirection.Output }
        );

        return ((IDbDataParameter)db.Command.Parameters["@XML"]).Value?.ToString();
    }

My calling method looked like this:

    public static void UpdateCustomerNote(int custId, string note)
    {
        using (var db = new L2DB())
        {
            var beforeXml = db.GetRecordStateXml("Customers", "CustomerId", custId);
            db.Customers.Where(c => o.CustomerId == custId)
                        .Set(c => c.Note, note)
                        .Update();   //ERROR: already an open DataReader
            var afterXml = db.GetRecordStateXml("Customers", "CustomerId", custId);

            //...xml is used identify changed fields and generate an audit trail
        }
    }

As you see, there are no nested loops or anything else that suggests the issues that my google search results suggested MUST be present.

In the past, out of desperation, I have run every single statement in its own `using` block, but today I finally found a solution. Two, actually.

The first solution I stumbled upon was replacing the `return` statement of the method that called the stored procedure with these three lines:

    var retval = ((IDbDataParameter)db.Command.Parameters["@XML"]).Value?.ToString();
    db.Close();  //this is the important addition
    return retval;

Ensuring that the data reader closed made the errors go away right away. But in the course of writing this post, I realized, to my horror, that there was a much easier solution, and that a loop had been hiding in plain sight the whole time. No doubt you saw it right away. I did not.

`QueryProc<T>()` has a return type of `IEnumerable<T>`, which means that there was a loop after all. Even though I'm not using any returned results, the un-iterated `IEnumerable<int>`, known only to the `DataConnection` internals, persisted and therefore kept open the `DataReader`.

The fix?

    public static string GetRecordStateXml(this L2DB db, string tableName, string primaryKeyName, int id)
    {
        db.QueryProc<int>("dbo.GetRecordStateXml",
            //same parameters as before
        ).ToArray(); //bring any results into memory, allowing the DataReader to close

        return ((IDbDataParameter)db.Command.Parameters["@XML"]).Value?.ToString();
    }

I know this isn't really the right place for a rant, but given the number of hours of my life spent on this, I'm hoping my venting helps someone else solve a similar issue. I consider both solutions valuable; the second is better for this specific case, but the former (`db.Close()`) is a quick and dirty fix with the ability to solve this problem almost anywhere.

**Comment by sdanyliv** [comment]
@dipique, can you open new issue with this text? It is definitely bug in T4 generation. It should be `ExecuteProc`. `QueryProc` returns `IEnumerable` which should be disposed.

**Comment by dipique** [comment]
> @dipique, can you open new issue with this text? It is definitely bug in T4 generation. It should be `ExecuteProc`. `QueryProc` returns `IEnumerable` which should be disposed.

As I mentioned in my comment, that method was hand-written. I don't have any specific/replicable  example of the same issue being generated from a T4 template.
