### ISSUE TITLE
[Task] Remove `DoNotClearOrderBys` option

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#4557]
Option was introduced by https://github.com/linq2db/linq2db/pull/467. Remove reasons:

- it is broken as side-effect of https://github.com/linq2db/linq2db/pull/4548 and require a ugly workarounds to fix it
- feature itself introduce illogical behavior we don't want to promote

**Comment by joonatanu-softwerk** [comment]
For dynamic generation of multiple order by fields, what would be the recommended approach?

We have some code that generates a bunch of expressions and applies those expressions as an argument for `Queryable.OrderBy()`. How to get similar behaviour without `DoNotClearOrderBys`?

From consistency perspective of "public API", it does make more sense to have it. If you have multiple `Queryable.Where()` clauses, the latter does not overwrite the earlier ones. Why should OrderBys do that?

**Comment by MaceWindu** [comment]
@sdanyliv, FYI

**Comment by MaceWindu** [comment]
@jogibear9988 , ping

**Comment by viceroypenguin** [comment]
@joonatanu-softwerk 

> From consistency perspective of "public API", it does make more sense to have it. If you have multiple `Queryable.Where()` clauses, the latter does not overwrite the earlier ones. Why should OrderBys do that?

Namely, because that's how `OrderBy` was designed when it was introduced in 2008. That's how Linq to Objects works, that's how every other linq-based ORM works. linq2db is unique in allowing multiple `OrderBy`s. 

Note that the difference between `OrderBy` and `Where` is that `Where` does not have a concept of "first" and "others" - all `Where` clauses are the same. As such, it doesn't _need_ to worry about whether to overwrite or not, it can just append. However, `OrderBy` does have the principle of ordering and "first" vs "others". This is because order matters inherently for sorting. As such, there is `OrderBy` and `ThenBy`, and most LINQ-based systems operate under the principle of `.OrderBy().ThenBy().ThenBy()`. 

The way to do dynamic ordering is to track your sort properties and then do:
```cs
var x = _db.Table.OrderBy(properties.First());

foreach (var p in properties.Skip(1))
  x = x.ThenBy(p);
```

**Comment by viceroypenguin** [comment]
@jogibear9988 I would like to ask you what specifically you are doing that is relying on this, and why it could not be done via `ThenBy`. I'm in favor of removing `DoNotClearOrderBys`, especially if it is going to make our code more complicated to maintain (see: bug that started this issue).

**Comment by jogibear9988** [comment]
@viceroypenguin look at the test here: https://github.com/linq2db/linq2db/pull/467/files#diff-a64b54ff2f4fafeab96949dc40d49e2ce8f4e278b8a06a66d9775867703d6e53R173

We compose queries in our code, and have some projections. So we do not have a IOrderedQueryable any more, so we can not call "Thenby"

**Comment by joonatanu-softwerk** [comment]
> @joonatanu-softwerk
> 
> > From consistency perspective of "public API", it does make more sense to have it. If you have multiple `Queryable.Where()` clauses, the latter does not overwrite the earlier ones. Why should OrderBys do that?
> 
> Namely, because that's how `OrderBy` was designed when it was introduced in 2008. That's how Linq to Objects works, that's how every other linq-based ORM works. linq2db is unique in allowing multiple `OrderBy`s.

Yes, it's true. It is still weird for me that it was designed like that, but the consistency argument is not really argument towards only Linq2Db, but to Microsoft and IQueryable itself.

> Note that the difference between `OrderBy` and `Where` is that `Where` does not have a concept of "first" and "others" - all `Where` clauses are the same. As such, it doesn't _need_ to worry about whether to overwrite or not, it can just append. However, `OrderBy` does have the principle of ordering and "first" vs "others". This is because order matters inherently for sorting. As such, there is `OrderBy` and `ThenBy`, and most LINQ-based systems operate under the principle of `.OrderBy().ThenBy().ThenBy()`.
> 
> The way to do dynamic ordering is to track your sort properties and then do:
> 
> ```cs
> var x = _db.Table.OrderBy(properties.First());
> 
> foreach (var p in properties.Skip(1))
>   x = x.ThenBy(p);
> ```

Seemingly simple, but can't really fit that in. The orderings may come from many places, therefore i don't know, if there is a "first order to skip in loop" and handle the "first one" separately.
I have resorted now to typecheck the queryable (because input and output will be always queryable) to understand if i have to use the "ThenBy*" methods or can use "OrderBy" methods. Together with possibility to reverse the order, i do have 2x2 matrix to figure eventually, which method i should call in the end.

So while i have managed to handle it on my own, this discussion may still be good food for thought. :)

**Comment by sdanyliv** [comment]
@jogibear9988 
> We compose queries in our code

Why ordering is a part of composing? LINQ design do no guaranteethat. Maybe we can find better way than adding additional hacks to the LINQ Translator.

**Comment by jogibear9988** [comment]
> @jogibear9988
> 
> > We compose queries in our code
> 
> Why ordering is a part of composing? LINQ design do no guarantee that. Maybe we can find better way than adding additional hacks to the LINQ Translator.

It works also in linq2objects:

https://dotnetfiddle.net/LJKGf1

**Comment by MaceWindu** [comment]
Well, technically it works like that due to internal implementation, not by-specification

**Comment by jogibear9988** [comment]
is there a specification wich says how a orderby before a projection should be handled?

**Comment by MaceWindu** [comment]
It has nothing to do with projections and OrderBy location. `OrderBy[Descending]` starts declaration of sort and `ThenOrderBy[Descending]` update it with additional sort instructions. Any other sort instructions before `OrderBy[Descending]` are ignored.

**Comment by jogibear9988** [comment]
> It has nothing to do with projections and OrderBy location. `OrderBy[Descending]` starts declaration of sort and `ThenOrderBy[Descending]` update it with additional sort instructions. Any other sort instructions before `OrderBy[Descending]` are ignored.

Where is it defined that the before ones are ignored? I also can join a ordered List, is there the sorting also ignored? And if I do a projection I loose the ordering

**Comment by viceroypenguin** [comment]
@jogibear9988 https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.orderby?view=net-8.0
![image](https://github.com/user-attachments/assets/42c504ec-7561-4e40-b3d1-ad4176f6b966)

This has been the expected behavior since it was introduced in 2008, and the matching `Queryable.OrderBy` has operated the same way in LinqToSQL, EF, EFC, and all other linq-based ORMs today.

**Comment by viceroypenguin** [comment]
> > @jogibear9988
> > Why ordering is a part of composing? LINQ design do no guarantee that. Maybe we can find better way than adding additional hacks to the LINQ Translator.
> 
> It works also in linq2objects:
> 
> https://dotnetfiddle.net/9KPYsj
> 
> ret1 is the results i want

The fact that it works like this is an implementation detail. The linq to objects internal implementation uses a "stable sort" - this means that if `a` is before `b` linearly in the sequence before the sort, and `a == b`, then `a` will remain before `b` after the sort. 

Notice also that `ret1` is equivalent to `lst.OrderBy(x => x.a).ThenBy(x => x.b)` (aka `ret4`), which is not the same thing as `lst.OrderBy(x => x.b).ThenBy(x => x.a)`. Your specified preference here is not the same thing as `DoNotClearOrderBy`, which would operate like the latter.

**Comment by MaceWindu** [comment]
This functionality was restored
