### ISSUE TITLE
Cassandra provider

### ISSUE THREAD

**Issue by MonDeveloper** [linq2db/linq2db#552]
I'm wondering if you could evaluate to add a provider for Cassandra, the Datastax Comunity C# driver is rock solid but unfortunately they removed the compatibility with EF.

**Comment by sdanyliv** [comment]
For which compatibility you are looking for?

**Comment by ili** [comment]
In general yes, but is it really good idea? 
Cassandra is NoSql solution & CQL is has just looks like SQL. I'v done a breath look on CQL no joins, no grouping, even not sure subqueries are supported (and really it would be strange if yes :)) 
I think that's why they just removed EF support.
Linq2db is a mostly type safe SQL, and trying to use SQL solution for NoSql, kills the idea of the second one

**Comment by MonDeveloper** [comment]
You're right. I agree. Until the EF Core.
Starting from EF Core, if you are thinking to an evolution of Linq2db, you should keep the door open also for non relational DB.
Anyway, thanks for the time you dedicate to my question.
