### ISSUE TITLE
Reenable 2 Ormbattle Tests on OSX

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#592]
When https://github.com/dotnet/corefx/issues/9649 is fixed, we should reenable "SelectSubqueryTest" & "ComplexTest1" so we see the stacktrace and can fix them.

**Comment by jogibear9988** [comment]
Is it ok, that I convert the netcore packages to the new csproj format?

**Comment by ili** [comment]
@jogibear9988 sorry for late response.
You can convert them. Also appveyor reconfiguration would be needed, because now we do use VS2015, and we'll use it in future while we do need to support silverlight, so we'll need to have two build configurations... or may me image can be switched with matrix...

**Comment by ili** [comment]
Guys from AV are very friendly :) They have added SL SDK adter my request :)

**Comment by MaceWindu** [comment]
@GonzoSpire can you remove Ignore attributes from OrmBattleTests tests and set ActiveIssue if some of them still fail?

**Comment by MaceWindu** [comment]
not actionable
