### ISSUE TITLE
[Idea] FodyAddin for linq2db

### ISSUE THREAD

**Issue by Int32Overflow** [linq2db/linq2db#662]
What are your thoughts about the idea of ​​building an addin of fody for linq2db?

An Addin of Fody (https://github.com/Fody/Fody) can modify the IL-Code at compile time. 

For example, you could automatic create CompiledQuery at compile time. This improves the performance of linq2db and the developer does not have to write it himself.

**Comment by sdanyliv** [comment]
@Int32Overflow, never heard about that but it is interesting.
I have no idea how it can be used in our current code, but for users - possible we can grab local Expression Trees into some static class and reuse them - it may really improve server's performance because not needed instantiation of Expression Tree on every function call.

**Comment by ili** [comment]
Generating CompiledQuerys would be great, but it is not so easy because of query composition :((

**Comment by Int32Overflow** [comment]
Yes, but maybe we can try it? You can implement complicated things in fody (Look at the many addins...)

**Comment by ili** [comment]
PR? :)

**Comment by MaceWindu** [comment]
Closing due to lack of interest. Currently we don't have resources for something like that, but we are open for PRs.
