### ISSUE TITLE
linq2db doesn't parameterize all parameters in update query

### ISSUE THREAD

**Issue by alifshits** [linq2db/linq2db#97]
We use linq2db v. 1.0.3 and PostgreSQL.
InlineParameters is false.
We have c# code:

``` c#
 _repository
                .Table()
                .Where(x => x.ID == gameElement.Id)
                .Set(x => x.Name, gameElement.Name)
                .Set(x => x.ModificationDateUtc, gameElement.ModifiedTime)
                .Update();
```

It produces following sql:

``` sql
-- Postresql.Local PostgreSQL
-- DECLARE p1 DateTime
-- DECLARE Id Int32

-- SET p1 = 17.07.2014 10:28:21
-- SET Id = 2

UPDATE
    "GameElement"
SET
    "Name" = 'Npgsq''lException',
    "ModificationDateUtc" = :p1
WHERE
    "GameElement"."ID" = :Id
```

Only ID and ModificationDateUtc set as command parameters, others parameters set as pure values. That's NOT OK

When code is the following:

``` c#
...
Set(x => x.Name, () => gameElement.Name)
...
```

linq2db passes it as command parameter. That's OK.

Is there is a way to force linq query provider generate parameterized sql? It's a bit uncomfortable to wrap all values into expressions.

**Comment by 10der** [comment]
Igor, another question about this issue.
how I can add SQL Parameter dynamically?
if I try to add params like this 
{code}
expressionsToAdd.Add(new SelectQuery.SetExpression(lastAccessUserIdField, new SqlParameter(typeof(int), "LastAccessUserId", userId)));
{code}
I got error: Must declare the scalar variable "@LastAccessUserId".

**Comment by igor-tkachev** [comment]
What do you need to do?

**Comment by 10der** [comment]
>What do you need to do?
```
 expressionsToAdd.Add(new SelectQuery.SetExpression(fld, new SqlValue [skiped]
```
this is work properly! But now we have SQL overhead (sql recompilation / etc)
We want Replace all SqlValue by SqlParameter 
but this code doesn't work (and I understand why, but not understand how resolve it)
```
expressionsToAdd.Add(new SelectQuery.SetExpression(fld, new SqlParameter( [skiped]
```

**Comment by ferbenor** [comment]
Mr. Igor can you help me with this pull tank you.
https://github.com/linq2db/linq2db/pull/231

**Comment by igor-tkachev** [comment]
>ps: we are need automatically fill some "fiscal" fields in table when table is updated/inserted by user UI
I think it is possible to solve this problem without changing the library.

**Comment by 10der** [comment]
>I think it is possible to solve this problem without changing the library.
so, we cannot use SqlParameter for passing own params to SQL Update query.
sad. OK

**Comment by fddima** [comment]
@igor-tkachev No, it is impossible achieve expected result without linq2db modding.
I'm think that it is common task, that it will be very nice to have some standard solution for this.
Main problem, that linq queries parameterized from expressions, but not from sql query (SelectQuery) and it is no way to extend parameterization dynamically from existing extension points.

But trying to achieve this result via DataConnection.ProcessQuery, like @10der do - it is wrong way anyway, 'because ProcessQuery anyway called once for parameterized queries.

Note, for me it is very unclear how ProcessQuery and FinalizeQuery differs. Why ProcessQuery exist? I'm see that ProcessQuery can be easily overloaded, but how queries cached? Via injecting at FinalizeQuery we can be sure that have correct result all time. With ProcessQuery i'm not sure...

So, solution is - process expression trees, but i'm not found useful extension points. (What i'm miss?). In same time processing queries as queries via SelectQuery are anyway simpler in some cases / this case.

Any way I'm assume that we want process queries implicitly. May be exist other techniques to achieve same or similar result?

My possible solution:

1. We should provide consistent query transformations. I'm use SqlOptimizer.Finalize for this purposes. See code for demo https://gist.github.com/fddima/d4cef497bdf1bb032f2e#file-mydataprovider-cs . (Actual logic i'm get from above comments).

2. Query paramter added later: https://gist.github.com/fddima/d4cef497bdf1bb032f2e#file-query-cs-additional-parameterization-demo-diff

It works, as expected. Not too complex.

@igor-tkachev May be have sense provide API to introduce dynamic parameters in some way (extend Finalize, or additional method, i'm no idea what's choice will be better for linq2db).
